version: '3'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: mediumclone
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mediumclone
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./cache:/data